### ISSUE TITLE
Sidekiq 7 Support

### ISSUE THREAD

**Issue by soberstadt** [fastly/sidekiq-prometheus#34]
I see that the sidekiq version was locked to `< 7` in #32, do you know what work would be outstanding to update sidekiq-prometheus to support sidekiq 7? I would be able to help if this is something this project is interested in.

**Comment by leklund** [comment]
Sorry I haven't had a chance to look into Sidekiq 7 support. I'll try to take a first pass at this in the next few days.

**Comment by soberstadt** [comment]
For what it's worth to anyone else. We ended up just implementing a simple set of sidekiq status APIs and the Ops team is polling that. I copied liberally from GitLab's implementation: https://gitlab.com/gitlab-org/gitlab/-/blob/8cdb4f0dfa301863a8c1928a1776f01442d7a342/lib/api/sidekiq_metrics.rb

**Comment by leklund** [comment]
@frederikspang This branch has experimental support for sidekiq 7: https://github.com/fastly/sidekiq-prometheus/compare/sk7?expand=1 I haven't tested against a functional app because the Rack >3.0 caused me issues. I'll probably back out the Rack upgrade as a separate change so I can test out this branch.

**Comment by frederikspang** [comment]
Damn - We're actually locked to Rack < 3 currently, because of `activerecord-session_store` internally.

And way we can avoid the >3.0 requirement?
Sidekiq 7 "only" has `rack (>= 2.2.4)` as requirement.

**Comment by leklund** [comment]
@frederikspang I updated the branch and so that it requires `rack <3.0`.
